### ISSUE TITLE
GTM v2 - undefined category and action / (not set) label

### ISSUE THREAD

**Issue by iuewebadmin** [robflaherty/riveted#21]
Hello!  I've followed the steps in Andy Gibson's blog post (awesome by the way!), but I think since I'm using GTM v2, I've been having some issues.  I had to remove the Event = 'ScrollDistance' trigger completely to get the event to fire at all.  After removing that, an event registers on page load in Google Analytics, but the Category and Action are both 'undefined', and the Label is '(not set)'; it also does not trigger additional events when scrolling down the page.

This is the Custom HTML tag containing scrolldepth.js:
![tag-scrolldepthjs](https://cloud.githubusercontent.com/assets/12818596/8598649/e0e97f70-2629-11e5-9e29-02b239219f96.png)

This is the tag that should be sending the variables to GA:
![tag-scrolldepth](https://cloud.githubusercontent.com/assets/12818596/8598810/eb8b752c-262a-11e5-9906-e849283f787a.png)

And this is the 'ScrollDistance' trigger:
![trigger-eventsscrolldistance](https://cloud.githubusercontent.com/assets/12818596/8599837/aa7c701c-2630-11e5-93cf-ee066c4905c6.png)

If I need to send any other screenshots, let me know.  Only other thing I can think of is that I tried both Data Layer Versions 1 and 2 for the custom variables with no difference.

Thanks for any suggestions!

**Comment by robflaherty** [comment]
GTM configuration is tricky. My only advice is to review each step and input in detail, compare it against Andy's instructions or the instructions from another post (there are a few others out there). These issues are usually due to one field value being slightly incorrect. "ScrollDepth" vs "ScrollDistance" or something like that.

Closing because this is a GTM config issue and not an issue with the plugin.

**Comment by iuewebadmin** [comment]
Thanks for the tip!  Sorry if I posted this in the wrong place.
