### ISSUE TITLE
when riverted started?

### ISSUE THREAD

**Issue by erikdemarco** [robflaherty/riveted#38]
Hello I'm confuse.

When is riveted start measuring time? during pageload or after page finished loading?
and why do you think that is the best scenario?

**Comment by robflaherty** [comment]
It starts measuring time as soon as one of these events fire:

      // Basic activity event listeners
      addListener(document, 'keydown', trigger);
      addListener(document, 'click', trigger);
      addListener(window, 'mousemove', throttle(trigger, 500));
      addListener(window, 'scroll', throttle(trigger, 500));

If you wanted the clock to start right away you could call the trigger method manually:

```
riveted.init();
riveted.trigger();
```

There's an argument for updating the plugin to start the clock immediately since we can assume that most users are actively engaged when they first load page.
